### ISSUE TITLE
Interferes with Windows key OS actions under XP

### ISSUE THREAD

**Issue by 4rc0s** [adampash/texter#1]
When I run Texter, at some point my Win keys stop functioning. I use Win-L all the time to lock my keyboard, Win-D to display the desktop, and Win-F to search for stuff.

**Comment by 4rc0s** [comment]
I just disabled compatibility mode and it looks like the windows keys are working again. Will investigate further.

Also, I may be talking to myself over here ;)

**Comment by mahalie** [comment]
I had the same issue. Windows+D and print screen were no longer working for me when Texter was enabled.  Assigned Ctrl+T to 'disable' so I could at least toggle it on/off. 

Windows Key + R for run still not working. When I toggle disable (Ctrl+T) Texter throws an Error: The following variable name contains an illegal character: "not foundKeys" The current thread will exit. Line#
--> 174: Bank := %Bank%

**Comment by mahalie** [comment]
p.s. Any random person reading this - don't use Ctrl+T! That's the shortcut for a new tab. Changed mine to Alt+X. (Which still throws the error mentioned above although it works)

**Comment by chappejw** [comment]
I was experiencing a bug in Texter where the application would throw this error as well, “Error: The following variable name contains an illegal character: “not foundKeys” “The current thread will exit. —> Line# 174: Bank:= Bank”
This meant that I had to restart the application again until it happened again. I narrowed this down to a bug when starting RDP and clicking on the RDP title bar or clicking into the username, password boxes of a remote system. The fix is as follows.
Change line line 164 of texter.ahk:
From:
if (SubStr(ErrorLevel, 1, 6) = “EndKey”)

To:
if (( SubStr( ErrorLevel, 1, 6 ) = “EndKey” ) AND ( SubStr( ErrorLevel, 8 ) != “not found” ))

This provides an additional condition for texter to catch all keys that are not found. This now seems to work reliably on Windows XP when using RDP.

**Comment by sdragnev** [comment]
I have a similar problem in Windows 7.

I have another program (PureText) running in the background which uses Windows + V to paste text as plain text.
When Texter is running, it just produces "v" when I pres Win + V.

This is not the only combination if keys broken. Also Ctrl + Shift + Alt + x in Notepad++ doesn't do anything.

I added the control keys to the ignore section in texter.ini and that fixed it.

**Comment by 4rc0s** [comment]
Interesting -- I'm having the same problem with PureText. I wish Texter would have the functionality of PureText.

**Comment by sdragnev** [comment]
Adding the following to the texter.ini in the ignore section fixed my PureText issues for the most part:

[Ignore]<br />
Keys={Tab},{Enter},{Space},{Ctrl},{Alt},{Shift},{LWin}

Of course that would mean that texter ignores those keys.

I don't know if it's a Windows 7 thing, but texter is a bit wonky sometimes. I often have to type a trigger word twice to get it to replace and sometimes it would still mess up my function keys that work other times...
So far it's a questionable convenience for me.

**Comment by 4rc0s** [comment]
Thanks for that tip. I only use Texter for text replacement anyway, so I wouldn't need those keys. (Hooray for limping along in Windows during my office day.)

**Comment by Rustamus** [comment]
Why is this topic closed? It still has same issue that Windows + L won't work when texter is active.
Also it gives error “Error: The following variable name contains an illegal character: “not foundKeys” “The current thread will exit. —> Line# 174: Bank:= Bank” when switching to RDP

Is there any solution? And switching from compatibility mode to clipboard is not an option

**Comment by adampash** [comment]
My apologies, Rustamis. I'm can no longer actively support this project, so
I won't be able to provide a solution.

Good luck!
Adam
